/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as GuidanceRouteImport } from './routes/guidance'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as MirrorRouteImport } from './routes/mirror'
import { Route as VersesRouteImport } from './routes/verses'
import { Route as ApiGuidanceRouteImport } from './routes/api/guidance'
import { Route as ApiMirrorRouteImport } from './routes/api/mirror'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidanceRoute = GuidanceRouteImport.update({
  id: '/guidance',
  path: '/guidance',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const MirrorRoute = MirrorRouteImport.update({
  id: '/mirror',
  path: '/mirror',
  getParentRoute: () => rootRouteImport,
} as any)
const VersesRoute = VersesRouteImport.update({
  id: '/verses',
  path: '/verses',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGuidanceRoute = ApiGuidanceRouteImport.update({
  id: '/api/guidance',
  path: '/api/guidance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMirrorRoute = ApiMirrorRouteImport.update({
  id: '/api/mirror',
  path: '/api/mirror',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/guidance': typeof GuidanceRoute
  '/journal': typeof JournalRoute
  '/mirror': typeof MirrorRoute
  '/verses': typeof VersesRoute
  '/api/guidance': typeof ApiGuidanceRoute
  '/api/mirror': typeof ApiMirrorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/guidance': typeof GuidanceRoute
  '/journal': typeof JournalRoute
  '/mirror': typeof MirrorRoute
  '/verses': typeof VersesRoute
  '/api/guidance': typeof ApiGuidanceRoute
  '/api/mirror': typeof ApiMirrorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/guidance': typeof GuidanceRoute
  '/journal': typeof JournalRoute
  '/mirror': typeof MirrorRoute
  '/verses': typeof VersesRoute
  '/api/guidance': typeof ApiGuidanceRoute
  '/api/mirror': typeof ApiMirrorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/guidance'
    | '/journal'
    | '/mirror'
    | '/verses'
    | '/api/guidance'
    | '/api/mirror'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/guidance'
    | '/journal'
    | '/mirror'
    | '/verses'
    | '/api/guidance'
    | '/api/mirror'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/guidance'
    | '/journal'
    | '/mirror'
    | '/verses'
    | '/api/guidance'
    | '/api/mirror'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  GuidanceRoute: typeof GuidanceRoute
  JournalRoute: typeof JournalRoute
  MirrorRoute: typeof MirrorRoute
  VersesRoute: typeof VersesRoute
  ApiGuidanceRoute: typeof ApiGuidanceRoute
  ApiMirrorRoute: typeof ApiMirrorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidance': {
      id: '/guidance'
      path: '/guidance'
      fullPath: '/guidance'
      preLoaderRoute: typeof GuidanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mirror': {
      id: '/mirror'
      path: '/mirror'
      fullPath: '/mirror'
      preLoaderRoute: typeof MirrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verses': {
      id: '/verses'
      path: '/verses'
      fullPath: '/verses'
      preLoaderRoute: typeof VersesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/guidance': {
      id: '/api/guidance'
      path: '/api/guidance'
      fullPath: '/api/guidance'
      preLoaderRoute: typeof ApiGuidanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mirror': {
      id: '/api/mirror'
      path: '/api/mirror'
      fullPath: '/api/mirror'
      preLoaderRoute: typeof ApiMirrorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  GuidanceRoute: GuidanceRoute,
  JournalRoute: JournalRoute,
  MirrorRoute: MirrorRoute,
  VersesRoute: VersesRoute,
  ApiGuidanceRoute: ApiGuidanceRoute,
  ApiMirrorRoute: ApiMirrorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
